// Mocks generated by Mockito 5.4.4 from annotations
// in chatos_test_app/test/comments_tests/comments_usecases_test/comments_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chatos_test_app/core/utils/errors/failures/failure.dart' as _i5;
import 'package:chatos_test_app/feature/projects_chat/domain/model/comment/comment_answer_model.dart'
    as _i9;
import 'package:chatos_test_app/feature/projects_chat/domain/model/comment/comment_model.dart'
    as _i8;
import 'package:chatos_test_app/feature/projects_chat/domain/model/comment/comments_model.dart'
    as _i6;
import 'package:chatos_test_app/feature/projects_chat/domain/model/issue/issue_model.dart'
    as _i7;
import 'package:chatos_test_app/feature/projects_chat/domain/repository/comments_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CommentsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentsRepository extends _i1.Mock
    implements _i3.CommentsRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CommentsModel>> getComments(
    String? email,
    _i7.IssueModel? issue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComments,
          [
            email,
            issue,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.CommentsModel>>.value(
                _FakeEither_0<_i5.Failure, _i6.CommentsModel>(
          this,
          Invocation.method(
            #getComments,
            [
              email,
              issue,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.CommentsModel>>.value(
                _FakeEither_0<_i5.Failure, _i6.CommentsModel>(
          this,
          Invocation.method(
            #getComments,
            [
              email,
              issue,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.CommentsModel>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i8.CommentModel>>> syncAnswerWithComment(
    List<_i8.CommentModel>? comments,
    _i9.CommentAnswerModel? answer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncAnswerWithComment,
          [
            comments,
            answer,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i8.CommentModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.CommentModel>>(
          this,
          Invocation.method(
            #syncAnswerWithComment,
            [
              comments,
              answer,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i8.CommentModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.CommentModel>>(
          this,
          Invocation.method(
            #syncAnswerWithComment,
            [
              comments,
              answer,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.CommentModel>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i8.CommentModel>>> syncAnswersWithComments(
    List<_i8.CommentModel>? comments,
    List<_i9.CommentAnswerModel>? answers,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncAnswersWithComments,
          [
            comments,
            answers,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i8.CommentModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.CommentModel>>(
          this,
          Invocation.method(
            #syncAnswersWithComments,
            [
              comments,
              answers,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i8.CommentModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.CommentModel>>(
          this,
          Invocation.method(
            #syncAnswersWithComments,
            [
              comments,
              answers,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.CommentModel>>>);
}
