// Mocks generated by Mockito 5.4.4 from annotations
// in chatos_test_app/test/projects_tests/projects_repository_test/projects_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chatos_test_app/feature/projects_chat/data/datasource/remote/projects_remote_datasource/projects_remote_datasource.dart'
    as _i3;
import 'package:chatos_test_app/feature/projects_chat/data/dto/project/projects_dto/projects_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProjectsDto_0 extends _i1.SmartFake implements _i2.ProjectsDto {
  _FakeProjectsDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProjectsRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectsRemoteDatasource extends _i1.Mock
    implements _i3.ProjectsRemoteDatasource {
  @override
  _i4.Future<_i2.ProjectsDto> getProjects(String? email) => (super.noSuchMethod(
        Invocation.method(
          #getProjects,
          [email],
        ),
        returnValue: _i4.Future<_i2.ProjectsDto>.value(_FakeProjectsDto_0(
          this,
          Invocation.method(
            #getProjects,
            [email],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ProjectsDto>.value(_FakeProjectsDto_0(
          this,
          Invocation.method(
            #getProjects,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.ProjectsDto>);
}
