// Mocks generated by Mockito 5.4.4 from annotations
// in chatos_test_app/test/comments_tests/comments_repository_test/comments_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chatos_test_app/feature/projects_chat/data/datasource/remote/comments_remote_datasource/comments_remote_datasource.dart'
    as _i3;
import 'package:chatos_test_app/feature/projects_chat/data/dto/comment/comments_dto/comments_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCommentsDto_0 extends _i1.SmartFake implements _i2.CommentsDto {
  _FakeCommentsDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CommentsRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentsRemoteDatasource extends _i1.Mock
    implements _i3.CommentsRemoteDatasource {
  @override
  _i4.Future<_i2.CommentsDto> getComments(
    String? email,
    String? issueId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComments,
          [
            email,
            issueId,
          ],
        ),
        returnValue: _i4.Future<_i2.CommentsDto>.value(_FakeCommentsDto_0(
          this,
          Invocation.method(
            #getComments,
            [
              email,
              issueId,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.CommentsDto>.value(_FakeCommentsDto_0(
          this,
          Invocation.method(
            #getComments,
            [
              email,
              issueId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.CommentsDto>);
}
