// Mocks generated by Mockito 5.4.4 from annotations
// in chatos_test_app/test/sign_in_tests/sign_in_repsitory_test/sign_in_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chatos_test_app/feature/sign_in/data/datasource/remote/sign_in_remote_datasource.dart'
    as _i3;
import 'package:chatos_test_app/feature/sign_in/data/dto/user_dto/user_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserDto_0 extends _i1.SmartFake implements _i2.UserDto {
  _FakeUserDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SignInRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInDatasource extends _i1.Mock
    implements _i3.SignInRemoteDatasource {
  @override
  _i4.Future<_i2.UserDto> signIn(String? email) => (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [email],
        ),
        returnValue: _i4.Future<_i2.UserDto>.value(_FakeUserDto_0(
          this,
          Invocation.method(
            #signIn,
            [email],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.UserDto>.value(_FakeUserDto_0(
          this,
          Invocation.method(
            #signIn,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.UserDto>);
}
